"""empty message

Revision ID: ada86fb27be9
Revises: 1de6033ab0bb
Create Date: 2022-12-27 08:38:13.484106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ada86fb27be9"
down_revision = "1de6033ab0bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_date", sa.DateTime(), nullable=True),
        sa.Column("order_amount", sa.Float(), nullable=True),
        sa.Column("order_status", sa.String(), nullable=True),
        sa.Column("shipping_address", sa.Text(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_detail",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_detail")
    op.drop_table("order")
    # ### end Alembic commands ###
